//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCTESTEntities : DbContext
    {
        public MVCTESTEntities()
            : base("name=MVCTESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_ClassAcademicYear> t_ClassAcademicYear { get; set; }
        public virtual DbSet<t_Classes> t_Classes { get; set; }
        public virtual DbSet<t_ClassSection> t_ClassSection { get; set; }
        public virtual DbSet<t_Student> t_Student { get; set; }
        public virtual DbSet<t_Gender> t_Gender { get; set; }
    }
}
