//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ClassSection
    {
        public int ClassSection_ID { get; set; }
        public string ClassSection_SectionName { get; set; }
        public Nullable<int> ClassSection_ClassID { get; set; }
        public bool ClassSection_IsActive { get; set; }
    }
}
