//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Classes
    {
        public int Classes_ID { get; set; }
        public string Classes_ClassName { get; set; }
        public Nullable<bool> Classes_Active { get; set; }
    }
}
