//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ClassAcademicYear
    {
        public int ClassAcademicYear_ID { get; set; }
        public Nullable<System.DateTime> ClassAcademicYear_AcademicYearStart { get; set; }
        public Nullable<System.DateTime> ClassAcademicYear_AcademicYearEnd { get; set; }
        public string ClassAcademicYear_AcademicYear { get; set; }
        public string ClassAcademicYear_Session { get; set; }
        public Nullable<bool> ClassAcademicYear_IsActive { get; set; }
    }
}
