//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Student
    {
        public int Student_ID { get; set; }
        public string Student_StudentName { get; set; }
        public Nullable<System.DateTime> Student_AdmissionDate { get; set; }
        public Nullable<int> Student_Classes_ID { get; set; }
        public Nullable<int> Student_ClassSection_ID { get; set; }
        public Nullable<int> Student_RollNumber { get; set; }
        public string Student_StudentCardNo { get; set; }
        public string Student_StudentPassword { get; set; }
        public Nullable<int> Student_ClassAcademicYear_ID { get; set; }
        public Nullable<int> Student_ApplicantGender { get; set; }
        public string Student_BloodGroup { get; set; }
        public Nullable<bool> Student_IsAdmited { get; set; }
    }
}
